#!/usr/bin/env bash
# This script displays information about subdomains

# Function to check and print domain info
check_and_print() {
    local domain=$1
    local subdomain=$2
    local record_info=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION:')
    local record_type=$(echo $record_info | awk '{print $4}')
    local destination=$(echo $record_info | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
    # If subdomain is not provided
    for sub in www lb-01 web-01 web-02; do
        check_and_print $domain $sub
    done
else
    # If subdomain is provided
    check_and_print $domain $subdomain
fi
