#!/usr/bin/env bash
# This script configures a new Ubuntu machine to have a custom 404 page

# Update the package lists for upgrades and new package installations
apt-get update -y

# Install nginx
apt-get install -y nginx

# Start nginx
service nginx start

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Create a configuration file for the custom 404 page
echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	
	error_page 404 /404.html;
	location = /404.html{
	internal;
	}
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
