#!/usr/bin/env bash
# This script creates a PID file

# Create a PID file
echo $$ > /var/run/myscript.pid

# Define what to do upon receiving SIGTERM and SIGINT signals
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

# Display a message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
