#!/usr/bin/env bash
# This script manages the manage_my_process script

case $1 in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        k1=$(cat /var/run/my_process.pid)
        kill "$k1"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        k2=$(cat /var/run/my_process.pid)
        kill "$k2"
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
