#!/usr/bin/env bash
# This script prints numbers from 1 to 100

for k in {1..100}; do
    if (( k % 3 == 0 && k % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( k % 3 == 0 )); then
        echo "Fizz"
    elif (( k % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$k"
    fi
done
