#!/usr/bin/env bash
#Bash script that gives you information about the school file

F="school"

if [ -e "$F" ]
    then
    echo "school file exists"
    if [ -s "$F" ]
        then
        echo "$F file is not empty"
    else
        echo "$F file is empty"
    fi
    if [ -f "$F" ]
        then
        echo "$F is a regular file"
    fi
else
    echo "$F file does not exist"
fi
